// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package dbgen

import (
	"database/sql"
)

type AppAuthUser struct {
	ID           string
	Email        string
	PhoneNumber  sql.NullString
	Password     string
	IsVerifiedAt sql.NullString
	IsVerified   sql.NullBool
	Meta         interface{}
	CreatedAt    sql.NullString
	UpdatedAt    sql.NullString
}
